modules/main/routes.py
from flask import (
    Flask,
    render_template,
    request,session,
    url_for,
    redirect,
    flash,
    Blueprint,
    abort,
    jsonify
)

from struct import unpack

from flask_paginate import (
    Pagination,
    get_page_args
)

from modules.connect_sql import MySQL
from modules.config import Config

from modules.functions import (
    retrieveAdmins,
    isUserLoggedIn,
    sendUserToHome,
    getItemName,
    setUserLoggedIn,
    retrieveNameFromID
)

from modules.main.impl import (
    loginUser,
    retrieveUserData
)

main = Blueprint('main', __name__)

# Redirect user to /home directory.
@main.route("/", methods=["GET", "POST"])
def index():
    """ Posts """

    conf = Config()

    per_page = conf.PER_PAGE
    page, per_page, offset = get_page_args()

    with MySQL() as c:
        c.execute("SELECT * FROM posts")
        c.fetchall()
        num_rows = c.rowcount

    pagination = Pagination(page=page, per_page=per_page, total=num_rows, bs_version=4, alignment="center")

    with MySQL() as c:
        c.execute(f"SELECT post_id, post_title, post_content, DATE_FORMAT(post_date, '%d, %M, %Y at %h:%i %p') as post_date, author_id FROM posts ORDER BY post_id DESC LIMIT {offset}, {per_page}")
        result_post = c.fetchall()

    """ Account """
    # if user has ticked remember_me before, we set its session login to true and stop executing the code below.
    if(session.get("remember_me")):
        setUserLoggedIn(True)
        return render_template("index.html",
            active='home',
            pagination=pagination,
            news=result_post,
            admins=retrieveAdmins()
        )

    # if the method we get is not post, we send the user back to index.html

    if(request.method == "POST"):
        # set username variable to form input.
        # set password variable to password input.
        username = request.form.get("username")
        password = request.form.get("password")

        ret = loginUser(username, password)

        if(ret == 0):
            return jsonify(success=False, error_msg="Invalid username, please try again.")
        elif(ret == 1):
            return jsonify(success=False, error_msg="Wrong password, please try again.")
        if(ret == 2):
            flash("You have  successfully logged in", "success")
            return jsonify(success=True)

    return render_template("index.html",
            active='home',
            pagination=pagination,
            news=result_post,
            admins=retrieveAdmins()
        )

@main.route("/dashboard/<int:accountid>", methods=["GET", "POST"])
def dashboard(accountid):
    # if user is not logged in, show him an error message saying he can't access this page.
    if(not isUserLoggedIn()):
        return abort(403)

    # if the session accountid is not the same as accountid passed to dashboard param then don't allow this process.
    if(session.get('accountid') != accountid):
        return abort(403)

    result_account, result_skill, result_item = retrieveUserData(accountid)

    return render_template("dashboard.html",
        active='dashboard',
        account=result_account,
        skill=result_skill,
        item=result_item,
        admins=retrieveAdmins()
    )

@main.route("/logout")
def logout():
    # if user is not logged in, show him an error message saying he can't access this page.
    if(not isUserLoggedIn()):
        return abort(403)

    session.clear()
    flash("You have successfully logged out", "success")
    return sendUserToHome()

@main.route("/searchAPI", methods=["GET"])
def searchAPI():
    if(request.method == "GET"):
        username = request.args.get("username")

        with MySQL() as c:
            query = "SELECT accountID FROM accounts WHERE username LIKE %s"
            param = f"%{username}%"
            c.execute(query, param)

            result = c.fetchall()

            if not (result):
                return jsonify(username="null")

            usernames = []
            for row in result:
                usernames.append(retrieveNameFromID(row['accountID']))
            return jsonify(username=usernames)



@main.route("/search/", defaults={'username': None})
@main.route("/search/<username>")
def search(username):
    if(username == None):
        return render_template("search.html",
            username=username,
            active='search',
            admins=retrieveAdmins()
        )

    with MySQL() as c:
        c.execute("SELECT accountID FROM accounts WHERE username = %s", username)
        result = c.fetchone()

    result_account, result_skill, result_item = retrieveUserData(result['accountID'])

    return render_template("search.html",
        active='search',
        account=result_account,
        skill=result_skill,
        item=result_item,
        admins=retrieveAdmins()
    )

modules/posts/routes.py
from flask import (
    render_template,
    redirect,
    session,
    request,
    flash,
    Blueprint,
    abort
)

from modules.functions import (
    isUserLoggedIn,
    retrieveAdmins,
    sendUserToHome
)

from modules.posts.impl import (
    writePost,
    editPost,
    updatePost,
    deletePost,
)

posts = Blueprint('posts', __name__)

@posts.route("/news_write")
def news_write():
    # if the user is not signed in and logged in, disallow from accessing this link.
    if(not isUserLoggedIn()):
        return abort(403)

    return render_template("news_write.html",
        admins=retrieveAdmins()
    )

@posts.route("/news_edit/<int:postid>")
def news_edit(postid):
    # if the user is not signed in and logged in, disallow from accessing this link.
    if(not isUserLoggedIn()):
        return abort(403)

    result = editPost(postid)
    return render_template("news_edit.html",
        post_data=result,
        admins=retrieveAdmins()
    )

@posts.route("/write_success", methods=["POST"])
def write_success():
    # if the user is not logged in, disallow from accessing this link.
    if(not isUserLoggedIn()):
        return abort(403)

    title = request.form.get('news_title')
    content = request.form.get('news_message')
    author = session.get("accountid")

    writePost(title, content, author)

    flash("You have successfully posted the content", "success")
    return sendUserToHome()

@posts.route("/edit_success/<int:postid>", methods=["GET", "POST"])
def edit_success(postid):
    # if the user is not logged in, disallow from accessing this link.
    if(not isUserLoggedIn()):
        return abort(403)

    title = request.form.get('news_title')
    content = request.form.get('news_message')

    updatePost(title, content, postid)

    flash("You have successfully edited the content", "success")
    return sendUserToHome()

@posts.route("/write_delete/<int:postid>", methods=["GET", "POST"])
def write_delete(postid):
    # if the user is not logged in, disallow from accessing this link.
    if(not isUserLoggedIn()):
        return abort(403)

    deletePost(postid)

    flash("You have successfully deleted the content", "success")
    return sendUserToHome()

modules/templates/dashboard.html
{% extends "layout.html" %}

{% block title %}
<title>Project Open - Dashboard</title>
{% endblock %}

{% block content %}

<div class="card my-4">
    <h5 class="card-header bg-dark text-white">Your Statistics</h5>
    <div class="card-body">
        <table class="table table-striped">
            <tr>
                <td>AccountID:</td>
                <td>{{ account.accountID }}</td>
            </tr>
            <tr>
                <td>Username:</td>
                <td>{{ account.username }}</td>
            </tr>
            <tr>
                <td>Register Date</td>
                <td>{{ account.reg_date}}</td>
            </tr>
            <tr>
                <td>Last Login</td>
                <td>{{ account.last_log }}</td>
            </tr>
            <tr>
                <td>Money:</td>
                <td>${{ account.money }}</td>
            </tr>
            <tr>
                <td>Kills:</td>
                <td>{{ account.kills }}</td>
            </tr>
            <tr>
                <td>Deaths:</td>
                <td>{{ account.deaths }}</td>
            </tr>
            <tr>
                <td>Job:</td>
                <td>{{ getJobName(account.jobID) }}</td>
            </tr>
        </table>
    </div>
</div>
<div class="card my-4">
    <h5 class="card-header bg-dark text-white">Skills</h5>
    <div class="card-body">
        <table class="table table-striped">
            {% for skills in skill %}
            <tr>
                <td>{{ getSkillName(skills.skill_id) }}:</td>
                <td>{{ skills.value }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<div class="card my-4">
    <h5 class="card-header bg-dark text-white">Skills</h5>
    <div class="card-body">
        <table class="table text-center table-bordered">

            <thead>
                {% for items in item %}
                    <th>{{ getItemName(items.item_id) }}</th>
                {% endfor %}
            </thead>
            <tr>
                {% for items in item %}
                    <td>{{ items.value }}</td>
                {% endfor %}
            </tr>
        </table>
    </div>
</div>
{% endblock %}

modules/templates/index.html
{% extends "layout.html" %}

{% block title %}
<title>Project Open - Home</title>
{% endblock %}

{% block content %}
    <!-- Title -->

    {% if session.get('isAdmin')%}
        <a href="{{ url_for('posts.news_write') }}" class="btn btn-success btn-sm" role="button">Write Post</a>
    {% endif %}
    {% for n in news %}

        <h1 class="mt-4">{{ n.post_title }}</h1>
        <!-- Author -->
        <p class="lead">
            Author: {{ retrieveNameFromID(n.author_id) }}
        </p>
        <hr>
        <!-- Date/Time -->
        <p>Posted on {{ n.post_date }}</p>
        <hr>
        {{ n.post_content | safe }}

        {% if session.get('isAdmin') %}
            <a href="{{ url_for('posts.write_delete', postid=n.post_id) }}" class="btn btn-primary btn-sm" role="button">Dete Post</a>
            <a href="{{ url_for('posts.news_edit', postid=n.post_id) }}" class="btn btn-secondary btn-sm" role="button">Edit Post</a>
        {% endif %}
        <hr>
    {% endfor %}


    {{ pagination.info }}
    {{ pagination.links }}

{% endblock %}

modules/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}
    {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- include summernote css/js -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>


    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>

<body>
<div style="padding-top: 25mm">
    {% include "includes/navbar.html" %}
</div>

<!-- Page Content start -->
<div class="container" id="sidebar">
    {% include "includes/messages.html" %}
    <div class="row">
        <!-- Post Content Column start-->
        <div class="col-lg-8">
           {% block content %}

           {% endblock %}
        </div>
        <!-- Post Content Column end-->
        <!-- Sidebar start -->
        <div class="col-md-4">
            <!-- Account Authentication start -->
            {% include "includes/sidebar-account_form.html" %}
            <!-- Account Authentication end -->
            <!-- Social Media -->
            <div class="card my-4">
                <h5 class="card-header bg-dark text-white">Social Media</h5>
                <div class="card-body text-center">
                    <a style="padding:2px" class="fab fa-facebook-square fa-3x text-dark"></a>
                    <a style="padding:2px" class="fab fa-twitter-square fa-3x text-dark"></a>
                    <a style="padding:2px" class="fab fa-steam-square fa-3x text-dark"></a>
                </div>
            </div>
            <!-- Social Media End -->
            <!-- Server Information -->
            {% include "includes/sidebar-admins.html" %}
            <!-- Server Information End -->
        </div>
        <!-- Sidebar end -->
    </div>
</div>
<!-- Page Content start -->

  <!-- Footer -->
<footer class="py-3 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Project Open 2019</p>
    </div>
</footer>

<script>
    // Timer Notification Message, fade out in 2.5 seconds after shown.
    $('.alert').delay(2500).fadeOut(300);
</script>

</body>
</html>

modules/templates/news_edit.html
{% extends "layout.html" %}

{% block title %}
<title>Project Open - Editing Content</title>
{% endblock %}

{% block content %}
<form action="{{ url_for('posts.edit_success', postid=post_data.post_id) }}" method="POST">
    <div class="card my-4">
        <h5 class="card-header bg-dark text-white">Enter Title</h5>
        <input class="text-center" type="text" name="news_title" value="{{ post_data.post_title }}" required/>


        <br>
        <br>

        <h5 class="card-header bg-dark text-white">Edit Content</h5>
        <textarea id="summernote" name="news_message" required>{{ post_data.post_content|safe }}</textarea>
        <button class="btn btn-dark" type="submit">Finish</button>
    </div>
</form>

<script>
    // Summer Note
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>
{% endblock %}

modules/templates/news_write.html
{% extends "layout.html" %}

{% block title %}
<title>Project Open - Writing Content</title>
{% endblock %}

{% block content %}
<form action="{{ url_for('posts.write_success') }}" method="POST">
    <div class="card my-4">
        <h5 class="card-header bg-dark text-white">Enter Title</h5>
        <input class="text-center" placeholder="Title" type="text" name="news_title" required/>

        <br>
        <br>

        <h5 class="card-header bg-dark text-white">Enter Content</h5>
        <textarea id="summernote" name="news_message" required></textarea>
        <button class="btn btn-dark" type="submit">Post Content</button>
    </div>
</form>

<script>
    // Summer Note
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>
{% endblock %}

modules/templates/search.html
{% extends "layout.html" %}
{% block title %}
Search
{% endblock %}

{% block content %}
<script type="text/javascript">
    $(document).ready(function() {
        $("#search").keyup(function() {
            $("#listplayers").html(""); // clear data ready for appending.

            var value = $("#search").val(); // take data from search input.
            if(value) { // if value is not null run the code below.
                $.get("{{ url_for('main.searchAPI') }}", { // send a get request
                    username: value
                },
                function(data, status) {
                    $("#listplayers").html(""); // clear data ready for appending.
                    const iterator = data.username.values();
                    for (const value of iterator) {
                            $("#listplayers")
                                .append("<ul><li class='list-group-item'><a href='./"+ value +"'>" + value + "</a></li></ul>");
                    }
                });
            }
        });
    });
</script>

<h3>Username</h3>
<p>Insert the username of the player to see their statistics</p>

<div class="text-center">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text "><i class="fas fa-user"></i></span>
        </div>
        <input type="search" name="search" id="search" class="form-control" placeholder="Username" required>
    </div>
    <div class="list-group" id="listplayers"></div>
</div>
{% if username != None %}
    <div class="card my-4">
        <h5 class="card-header bg-dark text-white">{{ account.username }}'s Statistics</h5>
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                        <td>AccountID:</td>
                        <td>{{ account.accountID }}</td>
                </tr>
                <tr>
                    <td>Username:</td>
                    <td>{{ account.username }}</td>
                </tr>
                <tr>
                    <td>Register Date</td>
                    <td>{{ account.reg_date}}</td>
                </tr>
                <tr>
                    <td>Last Login</td>
                    <td>{{ account.last_log }}</td>
                </tr>
                <tr>
                    <td>Money:</td>
                    <td>${{ account.money }}</td>
                </tr>
                <tr>
                    <td>Kills:</td>
                    <td>{{ account.kills }}</td>
                </tr>
                <tr>
                    <td>Deaths:</td>
                    <td>{{ account.deaths }}</td>
                </tr>
                <tr>
                    <td>Job:</td>
                    <td>{{ getJobName(account.jobID) }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="card my-4">
        <h5 class="card-header bg-dark text-white">Skills</h5>
        <div class="card-body">
            <table class="table table-striped">
                {% for skills in skill %}
                <tr>
                    <td>{{ getSkillName(skills.skill_id) }}:</td>
                    <td>{{ skills.value }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="card my-4">
        <h5 class="card-header bg-dark text-white">Skills</h5>
        <div class="card-body">
            <table class="table text-center table-bordered">

                <thead>
                    {% for items in item %}
                        <th>{{ getItemName(items.item_id) }}</th>
                    {% endfor %}
                </thead>
                <tr>
                    {% for items in item %}
                        <td>{{ items.value }}</td>
                    {% endfor %}
                </tr>
            </table>
        </div>
    </div>
{% endif %}
{% endblock %}